In [2]:
import pandas as pd;

In [3]:
info = {
    "Name" : ["Raj","Sagarika","Moukhi"],
    "CGPA" : [9.5,9.98,8.5]
}

df = pd.DataFrame(info)

print(df)

       Name  CGPA
0       Raj  9.50
1  Sagarika  9.98
2    Moukhi  8.50

In [4]:
df

       Name  CGPA
0       Raj  9.50
1  Sagarika  9.98
2    Moukhi  8.50

In [7]:
#series

s=pd.Series([1,2,3,4,5]) #index == label
print(s)
print(type(s))

#access using idx
print(s[2])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
3

In [11]:
s=pd.Series([1,2,3,4,5],index=["Adam","Eve","Raj","Sag","Moki"]) #index != labels
print(s)

#access using labels
print(s["Adam"])
print(s["Raj"])

#access using idx
print(s[2]) #iloc needed

print(s.index) #all labels

Adam    1
Eve     2
Raj     3
Sag     4
Moki    5
dtype: int64
1
3
3
Index(['Adam', 'Eve', 'Raj', 'Sag', 'Moki'], dtype='object')

C:\Users\HP\AppData\Local\Temp\ipykernel_29300\1815618933.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[2]) #iloc needed

In [12]:
#Series properties 

#homogenous values
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([10,20,30,40,50])

#vectorization
print(s1+s2)

#mutable values, immutable size
changed_s1=s1.drop(0)

print(s1)
print(changed_s1)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    1
1    2
2    3
3    4
4    5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [16]:
#dataframe 

#dictionary of lists 
info = {
    "Name":["Alice","Bob","Raj","Sag"],
    "Age":[10,16,18,24]
}

df=pd.DataFrame(info)

print(df,type(df))

#labels
print(df.index)
print(df.columns)

#list of lists 

import numpy as np

arr=np.array([[1,2,3],[4,5,6]])
df2=pd.DataFrame(arr,columns=["A","B","C"])

print(df2)

    Name  Age
0  Alice   10
1    Bob   16
2    Raj   18
3    Sag   24 <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=4, step=1)
Index(['Name', 'Age'], dtype='object')
   A  B  C
0  1  2  3
1  4  5  6

In [17]:
#Read data from csv file

df=pd.read_csv("employee_data.csv")
print(df)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [26]:
#Read data from json file 

df=pd.read_json("employee_data.json")
print(df)

print("-----------------df methods--------------------")
#dataframes methods
print(df.head()) #1st 5 row val
print("-----------------------------------------------")
print(df.tail(2)) #last 2 row val
print("-----------------------------------------------")
print(df.sample())#random row
print("-----------------------------------------------")
print(df.info()) #summary
print("-----------------------------------------------")
print(df.shape) #(row,col)
print("-----------------------------------------------")
print(df.describe()) #numerical summary (25% ===>  25%<=x , mean , std)
print("-----------------------------------------------")
print(df.columns)
print("-----------------------------------------------")
print(df.nunique()) # unique no. of ele in each col
print("-----------------------------------------------")

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000
-----------------df methods--------------------
   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
-----------------------------------------------
   ID   Name  Age Department  Salary
8   9    Ian   35         IT   75000
9  10  Julia   30    Finance   60000
-----------------------------------------------
   ID   Name  Age Department  Salary
0   1  Alice   25         HR   55000
-----------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes
None
-----------------------------------------------
(10, 5)
-----------------------------------------------
             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000
-----------------------------------------------
Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')
-----------------------------------------------
ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64
-----------------------------------------------

In [48]:
df=pd.read_csv("globalAirQuality.csv") #data from kaggle 

df.describe()

#select cols
df["city"] #view
place=df["city"].copy()#copy
df[["city","aqi"]]

#select rows - loc , iloc
df.loc[2]
df.loc[0:2] # 2=inclusive
df.iloc[2]
df.iloc[0:2] # 2=exclusive

#select cells - row,col
df.loc[0,["city","aqi"]]
df.iloc[0,2]

#select a single scalar value - at & iat
df.at[0,"city"]
df.iat[0,2]

'New York'

In [35]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [59]:
#filtering of data 

df[df["aqi"]>100]
df[(df["aqi"]>100) & (df["temperature"]>30)]
df[(df["aqi"]>100) & (df["temperature"]<30)]

aqi_data = df[df["aqi"]>100][["city","aqi"]] #chaining
aqi_data

aqi_data.iloc[1]
aqi_data.loc[3]

city    New York
aqi          158
Name: 3, dtype: object